### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by aolney** [StickmanVentures/ginger#18]
The root license is Apache-2.0 but app/static/model/README.md says CCA-NC?

**Comment by justinribeiro** [comment]
Correct; the code is under Apache-2.0, but the model is under CCA-NC. The model was included as a convenience to get the build up and running (as people initially had trouble).

**Comment by aolney** [comment]
Gotcha. I might suggest clarifying that on the root README. I was surprised to find another license hidden in the README of a nested folder.
